//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Common/Settings/VuforiaSamples_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VuforiaSamplesActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VuforiaSamplesActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VuforiaSamples_Actions"",
    ""maps"": [
        {
            ""name"": ""Vuforia"",
            ""id"": ""e8fdae9e-e542-44c4-9051-18787be9c246"",
            ""actions"": [
                {
                    ""name"": ""Tap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""293bd234-02ec-491d-bfc8-236ebda8c36f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DoubleTap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5a43640e-bb5b-4d34-b04d-6c6bb7fb7ac4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Press"",
                    ""type"": ""PassThrough"",
                    ""id"": ""71797f43-4e40-42ff-9034-6df3701c2c12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4d1638b5-a133-401d-b11a-640016c394e3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""19450fe3-2cf5-4a10-8bb1-25670ab3a37b"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": "";Touch"",
                    ""action"": ""DoubleTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33f859c9-e8f9-4b14-82ab-a906c2274a08"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""DoubleTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fad0dc8-2fa8-4912-95bf-2e3c90934e9f"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": "";Touch"",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75f86f1a-3694-4851-bcef-69735be00030"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51bb01d4-dddb-4584-ab78-35eca3418ddb"",
                    ""path"": ""<Pointer>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Touch;Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b3e4140-1509-4021-985e-86737a1b52a1"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Touch;Keyboard&Mouse"",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Vuforia
        m_Vuforia = asset.FindActionMap("Vuforia", throwIfNotFound: true);
        m_Vuforia_Tap = m_Vuforia.FindAction("Tap", throwIfNotFound: true);
        m_Vuforia_DoubleTap = m_Vuforia.FindAction("DoubleTap", throwIfNotFound: true);
        m_Vuforia_Press = m_Vuforia.FindAction("Press", throwIfNotFound: true);
        m_Vuforia_Point = m_Vuforia.FindAction("Point", throwIfNotFound: true);
    }

    ~@VuforiaSamplesActions()
    {
        UnityEngine.Debug.Assert(!m_Vuforia.enabled, "This will cause a leak and performance issues, VuforiaSamplesActions.Vuforia.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Vuforia
    private readonly InputActionMap m_Vuforia;
    private List<IVuforiaActions> m_VuforiaActionsCallbackInterfaces = new List<IVuforiaActions>();
    private readonly InputAction m_Vuforia_Tap;
    private readonly InputAction m_Vuforia_DoubleTap;
    private readonly InputAction m_Vuforia_Press;
    private readonly InputAction m_Vuforia_Point;
    public struct VuforiaActions
    {
        private @VuforiaSamplesActions m_Wrapper;
        public VuforiaActions(@VuforiaSamplesActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Tap => m_Wrapper.m_Vuforia_Tap;
        public InputAction @DoubleTap => m_Wrapper.m_Vuforia_DoubleTap;
        public InputAction @Press => m_Wrapper.m_Vuforia_Press;
        public InputAction @Point => m_Wrapper.m_Vuforia_Point;
        public InputActionMap Get() { return m_Wrapper.m_Vuforia; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VuforiaActions set) { return set.Get(); }
        public void AddCallbacks(IVuforiaActions instance)
        {
            if (instance == null || m_Wrapper.m_VuforiaActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VuforiaActionsCallbackInterfaces.Add(instance);
            @Tap.started += instance.OnTap;
            @Tap.performed += instance.OnTap;
            @Tap.canceled += instance.OnTap;
            @DoubleTap.started += instance.OnDoubleTap;
            @DoubleTap.performed += instance.OnDoubleTap;
            @DoubleTap.canceled += instance.OnDoubleTap;
            @Press.started += instance.OnPress;
            @Press.performed += instance.OnPress;
            @Press.canceled += instance.OnPress;
            @Point.started += instance.OnPoint;
            @Point.performed += instance.OnPoint;
            @Point.canceled += instance.OnPoint;
        }

        private void UnregisterCallbacks(IVuforiaActions instance)
        {
            @Tap.started -= instance.OnTap;
            @Tap.performed -= instance.OnTap;
            @Tap.canceled -= instance.OnTap;
            @DoubleTap.started -= instance.OnDoubleTap;
            @DoubleTap.performed -= instance.OnDoubleTap;
            @DoubleTap.canceled -= instance.OnDoubleTap;
            @Press.started -= instance.OnPress;
            @Press.performed -= instance.OnPress;
            @Press.canceled -= instance.OnPress;
            @Point.started -= instance.OnPoint;
            @Point.performed -= instance.OnPoint;
            @Point.canceled -= instance.OnPoint;
        }

        public void RemoveCallbacks(IVuforiaActions instance)
        {
            if (m_Wrapper.m_VuforiaActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVuforiaActions instance)
        {
            foreach (var item in m_Wrapper.m_VuforiaActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VuforiaActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VuforiaActions @Vuforia => new VuforiaActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    public interface IVuforiaActions
    {
        void OnTap(InputAction.CallbackContext context);
        void OnDoubleTap(InputAction.CallbackContext context);
        void OnPress(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
    }
}
